name: Build Windows Executable

on: [push]  # Ejecuta este workflow cada vez que haces un push al repositorio

jobs:
  build:
    runs-on: windows-latest  # Usa un entorno Windows en la nube

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Descarga el código del repositorio

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Define la versión de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python mediapipe pyinstaller  # Instala bibliotecas necesarias

      - name: Build executable
        run: pyinstaller --onefile body_capture.py  # Convierte tu script en un ejecutable .exe

      - name: Upload executable
        uses: actions/upload-artifact@v3  # Sube el .exe generado como "artifact"
        with:
          name: windows-executable
          path: dist/main.exe
