name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python-headless
          pip install mediapipe
          pip install "tensorflow<2.14"
          pip install pyinstaller

      - name: Create runtime-hook
        run: |
          echo 'import os
          import tensorflow as tf
          tf.keras.backend.clear_session()
          os.environ["CUDA_VISIBLE_DEVICES"] = "-1"' > tf_hook.py

      - name: Build executable with PyInstaller
        shell: cmd
        run: >-
          pyinstaller --onefile 
          --add-data "pose_landmark_lite.tflite;." 
          --add-data "hand_landmark.tflite;." 
          --hidden-import="mediapipe" 
          --hidden-import="cv2" 
          --hidden-import="tensorflow" 
          --additional-hooks-dir=hooks 
          --runtime-hook=tf_hook.py 
          --exclude-module=tensorflow.python.training.tracking.tracking 
          --exclude-module=tensorflow.python.training.tracking.util 
          --exclude-module=tensorflow.python.ops.gradients 
          body_capture.py

      - name: List files in dist folder
        run: dir dist

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: dist/body_capture.exe
