name: Build Windows Executable

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python mediapipe pyinstaller

      - name: Download MediaPipe models
        run: |
          curl -L -o pose_landmark_lite.tflite https://storage.googleapis.com/mediapipe-models/pose_landmark_lite.tflite
          curl -L -o hand_landmark.tflite https://storage.googleapis.com/mediapipe-models/hand_landmark.tflite

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --hidden-import=mediapipe --hidden-import=cv2 \
          --add-data "pose_landmark_lite.tflite;." --add-data "hand_landmark.tflite;." \
          body_capture.py

      - name: List files for debugging
        run: dir
        working-directory: dist

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: dist/body_capture.exe
