name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install opencv-python
          pip install mediapipe
          pip install "tensorflow==2.12.0"
          pip install cx_Freeze

      - name: Create runtime initialization
        shell: cmd
        run: |
          echo import os > init.py
          echo import numpy as np >> init.py
          echo import tensorflow as tf >> init.py
          echo os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' >> init.py
          echo os.environ['CUDA_VISIBLE_DEVICES'] = '-1' >> init.py

      - name: Build executable with cx_Freeze
        run: python setup.py build_exe

      - name: List files in build folder
        run: dir build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: build/
