name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python-headless mediapipe tensorflow pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --add-data "pose_landmark_lite.tflite;." --add-data "hand_landmark.tflite;." body_capture.py

      - name: List files in dist folder
        run: dir dist

      - name: Upload executable and models
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: |
            dist/body_capture.exe
            dist/pose_landmark_lite.tflite
            dist/hand_landmark.tflite
